// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGzvOyTOagOr88kR9LzG-RfJh8QmJEzs8',
    appId: '1:348559691653:web:83b126a55c29265346feec',
    messagingSenderId: '348559691653',
    projectId: 'time-reg-fb0a8',
    authDomain: 'time-reg-fb0a8.firebaseapp.com',
    storageBucket: 'time-reg-fb0a8.firebasestorage.app',
    measurementId: 'G-NN4064XZSW',
  );

  static const FirebaseOptions android = FirebaseOptions(apiKey: 'AIzaSyAotoYzm8rKyWYhe5gSxwsyj8m654WJAbY', appId: '1:348559691653:android:f9cda2bb29e33b0446feec', messagingSenderId: '348559691653', projectId: 'time-reg-fb0a8', storageBucket: 'time-reg-fb0a8.firebasestorage.app');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdjEehquMytxIjRC85T8I6o7i0fgaPlM',
    appId: '1:348559691653:ios:29e820cc72f393cd46feec',
    messagingSenderId: '348559691653',
    projectId: 'time-reg-fb0a8',
    storageBucket: 'time-reg-fb0a8.firebasestorage.app',
    iosBundleId: 'com.example.timeReg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdjEehquMytxIjRC85T8I6o7i0fgaPlM',
    appId: '1:348559691653:ios:29e820cc72f393cd46feec',
    messagingSenderId: '348559691653',
    projectId: 'time-reg-fb0a8',
    storageBucket: 'time-reg-fb0a8.firebasestorage.app',
    iosBundleId: 'com.example.timeReg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGzvOyTOagOr88kR9LzG-RfJh8QmJEzs8',
    appId: '1:348559691653:web:8ceb3560a43fe5ff46feec',
    messagingSenderId: '348559691653',
    projectId: 'time-reg-fb0a8',
    authDomain: 'time-reg-fb0a8.firebaseapp.com',
    storageBucket: 'time-reg-fb0a8.firebasestorage.app',
    measurementId: 'G-D8H73L8D6G',
  );
}
